apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: testing
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

