apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: helm-guestbook
spec:
 generators:
 - list:
     elements:
     - name: test1
       namespace: test1
       url: https://kubernetes.default.svc
       valuesfile: values-production.yaml
       values.port: NodePort
       values.replicaCount: 3
     - name: test2
       namespace: test2
       url: https://kubernetes.default.svc
       valuesfile: values-test.yaml
       values:
         port: LoadBalancer
         replicaCount: 1
 template:
   metadata:
     name: '{{name}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/andreaczar/test-infrastructure.git
       path: helm-guestbook
       targetRevision: HEAD
       helm:
         valueFiles:
           - '{{valuesfile}}'
         parameters:
           - name: service.type
             value: '{{values.port}}'
           - name: replicaCount
             value: '{{values.replicaCount}}'
     destination:
       server: '{{url}}'
       namespace: '{{namespace}}'
     syncPolicy:
       syncOptions:
         - CreateNamespace=true
