apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: helm-guestbook
spec:
 generators:
 - list:
     elements:
     - name: testing-dev
       namespace: default
       url: https://kubernetes.default.svc
       valuesfile: values-production.yaml
       values.port: NodePort
 template:
   metadata:
     name: '{{name}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/andreaczar/test-infrastructure.git
       path: helm-guestbook
       targetRevision: HEAD
       helm:
         valueFiles:
           - '{{valuesfile}}'
         parameters:
           - name: service.type
             value: '{{values.port}}'
     destination:
       server: '{{url}}'
       namespace: test
     syncPolicy:
       syncOptions:
         - CreateNamespace=true
